[da]
# The JWT used to authenticate with the celestia light client. Instructions for generating this token can be found in the README
celestia_rpc_auth_token = "MY.SECRET.TOKEN"
# The address of the *trusted* Celestia light client to interact with
celestia_rpc_address = "http://localhost:11111/"
# The largest response the rollup will accept from the Celestia node. Defaults to 100 MB
max_celestia_response_body_size = 104_857_600

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "benches/demo_data"

[runner]
# We define the rollup's genesis to occur at block number `start_height`. The rollup will ignore
# any blocks before this height
start_height = 1

[runner.rpc_config]
# the host and port to bind the rpc server for
bind_host = "127.0.0.1"
bind_port = 12345
