[package]
name = "sov-modules-api"
version = "0.1.0"
edition = "2021"


[dependencies]
sov-state = { path = "../sov-state" }
sovereign-sdk = { git = "https://github.com/Sovereign-Labs/sovereign-sdk" }
borsh = { workspace = true}


[features]
mocks = []
