[package]
name = "sov-modules-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
sov-state = { workspace = true }
sovereign-sdk = { workspace = true }
serde = { workspace = true }
borsh = { workspace = true}
thiserror = { workspace = true }
jmt = { workspace = true }
sha2 = { workspace = true }
bech32 = { workspace = true }

[features]
mocks = ["sov-state/mocks"]
