[package]
name = "integration-tests"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
tempfile = { workspace = true }

sov-modules-api = { path = "../../sov-modules-api", features = ["native"] }
sov-state = { path = "../../sov-state", features = ["native"] }
sov-rollup-interface = { path = "../../../rollup-interface" }
sov-schema-db = { path = "../../../full-node/db/sov-schema-db" }
sov-data-generators = { path = "../../utils/sov-data-generators" }
sov-modules-stf-template = { path = "../../sov-modules-stf-template", features = ["native"] }

sov-chain-state = { path = "../sov-chain-state", features = ["native"] }
sov-value-setter = { path = "../examples/sov-value-setter", features = ["native"] }
