[package]
name = "sov-accounts"
description = "A Sovereign SDK module for managing rollup state using accounts"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc"] }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
clap = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }

sov-modules-api = { path = "../../sov-modules-api", version = "0.1", default-features = false, features = ["macros"] }
sov-state = { path = "../../sov-state", version = "0.1", default-features = false }


[dev-dependencies]
sov-modules-api = { path = "../../sov-modules-api", version = "0.1" }
tempfile = { workspace = true }

[features]
default = ["native"]
arbitrary = ["dep:arbitrary", "sov-state/arbitrary"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde", "sov-state/native", "sov-modules-api/native", "dep:jsonrpsee", "dep:schemars", "dep:clap"]
