[package]
name = "sov-ibc-router"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dependencies]
anyhow = { workspace = true }
ibc = { workspace = true }
sov-ibc-transfer = { path = "../sov-ibc-transfer", default-features = false }
sov-modules-api = { path = "../../sov-modules-api", default-features = false, features = ["macros"] }
sov-state = { path = "../../sov-state", default-features = false }
sov-rollup-interface = { path = "../../../rollup-interface" }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"] }

[dev-dependencies]
sov-modules-api = { path = "../../sov-modules-api" }
tempfile = { workspace = true }

[features]
default = ["native"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde", "sov-modules-api/native", "dep:schemars"]
