[package]
name = "module-template"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
thiserror = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }

sov-bank = { path = "../sov-bank" }
sov-modules-api = { path = "../../sov-modules-api" }
sov-state = { path = "../../sov-state" }
sov-rollup-interface = { path = "../../../rollup-interface" }


[dev-dependencies]
tempfile = { workspace = true }
module-template = { path = ".", version = "*", features = ["native"] }

[features]
default = []
native = ["serde_json", "schemars", "sov-modules-api/native"]
