[package]
name = "tracer"
version = "0.2.0"
edition = "2018"

[workspace]

[dependencies]
rustc-demangle = "0.1.18"
goblin = "0.2"
capstone = "0.11.0"
regex = "1.5.4"
prettytable-rs = "^0.10"
textwrap = "0.16.0"
indicatif = "0.17.6"
clap = {version = "4.3.21", features = ['derive']}
