[package]
name = "sov-evm"
description = "A Sovereign SDK managing fungible tokens"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"


[dependencies]
revm = "3.3.0"
sov-modules-api = { path = "../../sov-modules-api", version = "0.1", default-features = false }
sov-modules-macros = { path = "../../sov-modules-macros", version = "0.1" }
sov-state = { path = "../../sov-state", version = "0.1", default-features = false }
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.1" }

anyhow = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
tracing = { workspace = true }

# TODO: move these dependencies to the workspace when the EVM module is no longer in the experimental stage
ethereum-types = "0.14.1"
ethers-core = "2.0.7"
ethers-contract = "2.0.7"
ethers-middleware = { version = "2.0.7"}
ethers-providers = { version = "2.0.7"}
ethers-signers = { version = "2.0.7", default-features = false }


[dev-dependencies]
primitive-types = "0.12.1"
sov-modules-api = { path = "../../sov-modules-api", version = "0.1" }

tokio = { workspace = true }
tempfile = { workspace = true }
bytes = { workspace = true }

[features]
default = ["native", "experimental"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde", "sov-state/native", "dep:jsonrpsee", "sov-modules-api/native"]
experimental = []
