[package]
name = "sov-evm"
description = "A Sovereign SDK managing fungible tokens"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"


[dependencies]

sov-modules-api = { path = "../../sov-modules-api", version = "0.1", default-features = false, features = ["macros"] }
sov-state = { path = "../../sov-state", version = "0.1", default-features = false }

anyhow = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
schemars = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc"] }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
tracing = { workspace = true }
derive_more = { workspace = true }

# TODO: move these dependencies to the workspace when the EVM module is no longer in the experimental stage
ethereum-types = "0.14.1"
ethers-core = { workspace = true }
ethers-contract = { workspace = true }
ethers-middleware = { workspace = true }
ethers-providers = { workspace = true }
ethers-signers = { workspace = true }



ethers = { workspace = true }

revm = { workspace = true }
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }
reth-rpc = { workspace = true }
reth-revm = { workspace = true }

secp256k1 = { workspace = true }

[dev-dependencies]

primitive-types = "0.12.1"
tokio = { workspace = true }
tempfile = { workspace = true }
bytes = { workspace = true }

sov-modules-api = { path = "../../sov-modules-api", version = "0.1", features = ["macros"] }

[features]
default = ["native", "experimental"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde", "sov-state/native", "dep:jsonrpsee", "dep:schemars", "sov-modules-api/native", "dep:clap"]
experimental = ["native"]

