[package]
name = "sov-evm"
description = "A Sovereign SDK managing fungible tokens"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"


[dependencies]

sov-modules-api = { path = "../../sov-modules-api", version = "0.2" }
sov-state = { path = "../../sov-state", version = "0.2" }

anyhow = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
schemars = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc"] }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
tracing = { workspace = true }
derive_more = { workspace = true }
lazy_static = "1.4.0"


ethereum-types = { workspace = true }
ethers-core = { workspace = true }
ethers-contract = { workspace = true }
ethers-middleware = { workspace = true }
ethers-signers = { workspace = true }
ethers = { workspace = true }

revm = { workspace = true, features = ["optional_block_gas_limit", "optional_eip3607", "optional_no_base_fee"] }
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }
reth-revm = { workspace = true }
secp256k1 = { workspace = true }

[dev-dependencies]
sov-evm = { path = ".", features = ["smart_contracts"] }
tokio = { workspace = true }
tempfile = { workspace = true }
bytes = { workspace = true }


[features]
default = []
native = ["serde", "serde_json", "jsonrpsee", "schemars", "clap", "sov-state/native", "sov-modules-api/native"]
experimental = ["native"]
smart_contracts = ["experimental"]

