[package]
name = "risc0-starter"
version = "0.3.0"
edition = "2021"
resolver = "2"
license = "MIT OR Apache-2.0"
publish = false

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest-mock"]

[features]
bench = []
