[package]
name = "sov-state"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO remove this dependency once the  Decode/Encode traits are extracted to a separate crate.
anyhow = { workspace = true }
borsh = { workspace = true}
thiserror = { workspace = true }
sovereign-db = { path = "../../db/sovereign-db", optional = true}
sovereign-sdk = { path = "../../sdk", features = ["mocks"] }
first-read-last-write-cache = { path = "../../first-read-last-write-cache" }
jmt = { workspace = true }
hex = { workspace = true}
sha2 = { workspace = true}

[dev-dependencies]
sovereign-db = { path = "../../db/sovereign-db", features = ["temp"] }
schemadb = { path = "../../db/schemadb", features = ["temppath"] }

[features]
default = ["native"]
temp = ["sovereign-db/temp"]
native = ["sovereign-db"]
