[package]
name = "sov-bank"
description = "A Sovereign SDK managing fungible tokens"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
clap = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }

sov-modules-api = { path = "../../sov-modules-api", version = "0.3" }
sov-state = { path = "../../sov-state", version = "0.3" }
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.3" }


[dev-dependencies]
sov-bank = { path = ".", features = ["native"] }
tempfile = { workspace = true }

[features]
default = []
native = [
    "serde_json",
    "jsonrpsee",
    "clap",
    "schemars",
    "sov-state/native",
    "sov-state/sov-db",
    "sov-modules-api/native",
]
cli = ["native"]
