[package]
name = "sov-demo-prover-guest"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]

[dependencies]
anyhow = "1.0.68"
risc0-zkvm = { version = "0.16", default-features = false, features = ["std"] }
risc0-zkvm-platform = "0.16"
borsh = { version = "0.10.3", features = ["bytes"] }
demo-stf = { path = "../../../demo-stf" }
sov-rollup-interface = { path = "../../../../rollup-interface", default-features = false }
sov-risc0-adapter = { path = "../../../../adapters/risc0" }
const-rollup-config = { path = "../../../const-rollup-config" }
sov-celestia-adapter = { path = "../../../../adapters/celestia" }
sov-modules-stf-template = { path = "../../../../module-system/sov-modules-stf-template", optional = true }
sov-state = { path = "../../../../module-system/sov-state", default-features = false, optional = true }
sov-modules-api = { path = "../../../../module-system/sov-modules-api", default-features = false, optional = true }
sov-sequencer-registry = { path = "../../../../module-system/module-implementations/sov-sequencer-registry", default-features = false, optional = true }

[build-dependencies]
directories = "5.0"
downloader = "0.2"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.6"
sha3 = "0.10.8"
tempfile = "3.5"
zip = "0.6"

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2/v0.10.6-risc0" }

[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

[features]
bench = [
	"sov-celestia-adapter/bench",
	"sov-modules-stf-template/bench",
	"sov-state/bench",
	"sov-modules-api/bench",
	"sov-sequencer-registry/bench",
]
