[package]
name = "sov-app-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
sovereign-sdk = { workspace = true }
sov-state = { workspace = true }
sov-modules-api = { workspace = true, default-features = false }
borsh = { workspace = true }
