[package]
name = "sov-data-generators"
description = "A set of generator utils used to automatically produce and serialize transaction data"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"
publish = false


[dependencies]
sov-modules-api = { path = "../../sov-modules-api", features = ["native"] }
sov-modules-stf-template = { path = "../../sov-modules-stf-template", features = ["native"] }
sov-value-setter = { path = "../../module-implementations/examples/sov-value-setter", features = ["native"] }
sov-bank = { path = "../../module-implementations/sov-bank", features = ["native"] }
sov-state = { path = "../../sov-state" }
sov-rollup-interface = { path = "../../../rollup-interface", features = ["mocks"] }

borsh = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
