[package]
name = "const-rollup-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jupiter = { path = "../../adapters/celestia", default-features = false }
