[package]
name = "first-read-last-write-cache"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = { workspace = true }


[dev-dependencies]
proptest = { workspace = true }
im = {workspace = true}
