[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dev-dependencies]
sov-modules-api = { path = "../../sov-modules-api", features = ["mocks"] }
sov-state = { path = "../../sov-state", features = ["temp"] }

[dependencies]
anyhow = { workspace = true }
bank = { path = "../bank" }
sov-modules-api = { path = "../../sov-modules-api" }
sov-modules-macros = { path = "../../sov-modules-macros" }
sov-state = { path = "../../sov-state" }
sovereign-sdk = { path = "../../../sdk" }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
hex = { workspace = true }


[features]
default = ["native"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde"]
