[package]
name = "sov-modules-stf-template"
description = "Defines a generic state transition function for use with the Sovereign SDK module system"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
jmt = { workspace = true }
hex = { workspace = true }

sov-rollup-interface = { path = "../../rollup-interface", version = "0.1" }
sov-state = { path = "../sov-state", version = "0.1" }
sov-modules-api = { path = "../sov-modules-api", version = "0.1" }
sov-zk-cycle-macros = { path = "../../utils/zk-cycle-macros", optional = true }
sov-zk-cycle-utils = { path = "../../utils/zk-cycle-utils", optional = true }
risc0-zkvm = { version = "0.16", default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { version = "0.16", optional = true }

[features]
bench = ["sov-zk-cycle-macros/bench", "sov-zk-cycle-utils", "risc0-zkvm", "risc0-zkvm-platform"]
default = []
native = ["sov-state/native", "sov-modules-api/native"]
