[package]
name = "sov-demo-avail-prover-host"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
risc0-zkvm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

presence = { path = "../../../adapters/avail" }
demo-stf = { path = "../../demo-stf" }
sov-rollup-interface = { path = "../../../rollup-interface" }
risc0-adapter = { path = "../../../adapters/risc0" }
sov-modules-api = { path = "../../../module-system/sov-modules-api", features = ["native"] }
sov-state = { path = "../../../module-system/sov-state", features = ["native"] }

methods = { path = "../methods" }
