# We define the rollup's genesis to occur at Avail block number `start_height`. The rollup will ignore
# any Avail blocks before this height
start_height = 163186
sequencer_da_address = "eab865bb6df6cf734ed7a0e193cfbc9378267d3d07acfd861132160293ce0f6b"

[da]
light_client_url = "http://127.0.0.1:8000"
node_client_url = "wss://kate.avail.tools:443/ws"

[runner.storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "demo_data"

[rpc_config]
# the host and port to bind the rpc server for
bind_host = "127.0.0.1"
bind_port = 12345
