[package]
name = "sov-ethereum"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"


[dependencies]
anyhow = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
serde = { workspace = true, features = ["derive"] }
sov-rollup-interface = { path = "../../rollup-interface" }
ethers = {version = "2.0.7"}

sov-evm = { path = "../../module-system/module-implementations/sov-evm", default-features = false, features = ["experimental"] }
demo-stf = { path = "../../examples/demo-stf", features = ["native", "experimental"] }
sov-modules-api = { path = "../../module-system/sov-modules-api", default-features = false }
const-rollup-config = { path = "../../examples/const-rollup-config" }
jupiter = { path = "../../adapters/celestia", features = ["native"] }

borsh = { workspace = true }
serde_json = { workspace = true }


[dev-dependencies]
sov-rollup-interface = { path = "../../rollup-interface", features = ["mocks"] }
tokio = { workspace = true }


[features]
default = ["native", "experimental"]
experimental =["demo-stf/experimental", "sov-evm/experimental"]

native = ["demo-stf/native", "sov-evm/native"]