[package]
name = "example-value-adder"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
sov-modules-api = { workspace = true ,  features = ["mocks"]}

[dependencies]
anyhow = { workspace = true }
sov-modules-api = { workspace = true }
sov-modules-macros = { workspace = true }
sov-state = { workspace = true }
sovereign-sdk = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true}
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"]}

[features]
default = ["native"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde"]