name: 'Downstream Repo Checks'
on:
  push:
    branches:
      - nightly

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger child repo workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: Sovereign-Labs
          repo: sov-rollup-starter
          github_token: ${{ secrets.CI_TRIGGER_ACCESS_TOKEN }}
          workflow_file_name: rust.yml
          ref: main
          wait_interval: 25
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
